export const GET_MESSAGES_REQUEST = '@@messages/GET_MESSAGES_REQUEST'
export const GET_MESSAGES_SUCCESS = '@@messages/GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILURE = '@@messages/GET_MESSAGES_FAILURE'

export const POST_MESSAGE_REQUEST = '@@messages/POST_MESSAGE_REQUEST'
export const POST_MESSAGE_SUCCESS = '@@messages/POST_MESSAGE_SUCCESS'
export const POST_MESSAGE_FAILURE = '@@messages/POST_MESSAGE_FAILURE'
