export const GET_MESSAGES_REQUEST = '@@messages/GET_MESSAGES_REQUEST'
export const GET_MESSAGES_SUCCESS = '@@messages/GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILURE = '@@messages/GET_MESSAGES_FAILURE'

export const GET_CHATS_REQUEST = '@@chats/GET_CHATS_REQUEST'
export const GET_CHATS_SUCCESS = '@@chats/GET_CHATS_SUCCESS'
export const GET_CHATS_FAILURE = '@@chats/GET_CHATS_FAILURE'

export const GET_CHAT_INFO_REQUEST = '@@messages/GET_CHAT_INFO_REQUEST'
export const GET_CHAT_INFO_SUCCESS = '@@messages/GET_CHAT_INFO_SUCCESS'
export const GET_CHAT_INFO_FAILURE = '@@messages/GET_CHAT_INFO_FAILURE'
