export const GET_MESSAGES_REQUEST = '@@messages/GET_MESSAGES_REQUEST'
export const GET_MESSAGES_SUCCESS = '@@messages/GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILURE = '@@messages/GET_MESSAGES_FAILURE'
