export const GET_LANGUAGES_REQUEST = '@@languages/GET_LANGUAGES_REQUEST';
export const GET_LANGUAGES_SUCCESS = '@@languages/GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAILURE = '@@languages/GET_LANGUAGES_FAILURE';